blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/your-org/krawl/security/policy
    about: Please report security issues privately via our Security Policy.
  - name: Documentation question
    url: https://github.com/your-org/krawl/discussions
    about: Use Discussions for general questions and input.

