# Development Environment Configuration
# Activate with: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev
# Or set environment variable: SPRING_PROFILES_ACTIVE=dev

# CORS Configuration for Development
cors:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000

# Development Logging - More verbose for debugging
logging:
  level:
    com.krawl.backend: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

