# Production Environment Configuration
# Activate with environment variable: SPRING_PROFILES_ACTIVE=prod
# IMPORTANT: Override CORS_ALLOWED_ORIGINS with your production domains

# CORS Configuration for Production
# Override this in your deployment platform with actual production URLs
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://krawl.vercel.app}

# JWT Configuration for Production
# Secure cookies required for HTTPS
jwt:
  cookie-secure: ${JWT_COOKIE_SECURE:true} # Always true in production (HTTPS)

# Production Logging - Less verbose, focus on errors and warnings
logging:
  level:
    com.krawl.backend: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Production optimizations for faster startup and better performance
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # Production optimizations
        temp.use_jdbc_metadata_defaults: false
        jdbc.batch_size: 20
  
  # Optimize connection pool for production
  datasource:
    hikari:
      # Production: keep more connections ready for faster response
      minimum-idle: ${DB_MIN_IDLE:5}
      # Ensure connections are validated before use
      connection-test-query: SELECT 1

# Email Configuration for Production
# IMPORTANT: For Render deployments, set MAIL_PROVIDER=mailjet, resend, or sendgrid
# SMTP ports (25, 587, 465) are blocked on Render
app:
  mail:
    # Use 'mailjet' (recommended - best free tier), 'resend', or 'sendgrid' for Render
    # Use 'smtp' for other platforms that support SMTP
    provider: ${MAIL_PROVIDER:mailjet}

