spring:
  application:
    name: backend

  # Database Configuration
  datasource:
    url: ${DATABASE_URL}?sslmode=${DB_SSLMODE:prefer}&prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: ${DB_POOL_SIZE:20}
      # Optimize for faster startup: reduce minimum idle connections in dev
      # Production will use higher value via application-prod.yaml
      minimum-idle: ${DB_MIN_IDLE:3}
      leak-detection-threshold: 60000
      # Don't fail startup if connection pool initialization takes time
      initialization-fail-timeout: -1

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Let Flyway handle schema
    show-sql: true  # Set to false in production via application-prod.yaml
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        # Optimize for faster startup - delay metadata scanning until first use
        temp.use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 20
          batch_versioned_data: true
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true

  # Mail (SMTP) - Only needed if MAIL_PROVIDER=smtp
  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:true}
          # SSL configuration (for port 465)
          ssl:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE:false}
            trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:*}
            protocols: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_PROTOCOLS:TLSv1.2}
          # Connection timeout settings (in milliseconds)
          # IMPORTANT: These must be positive integers. Negative values cause connection issues.
          connectiontimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:30000}
          timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:30000}
          writetimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:30000}
          # Socket factory for better SSL/TLS handling
          socketFactory:
            class: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKET_FACTORY_CLASS:javax.net.ssl.SSLSocketFactory}
            fallback: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKET_FACTORY_FALLBACK:false}
    default-encoding: UTF-8
    test-connection: false

  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    mixed: true
    validate-on-migrate: false
    locations: classpath:db/migration
    schemas: public
  
  # Cache Configuration
  cache:
    type: simple # ConcurrentMapCacheManager (can be upgraded to Redis/Caffeine)
    cache-names: tags,users,publicGems,publicKrawls

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Logging Configuration
# Production uses less verbose logging via application-prod.yaml
logging:
  level:
    com.krawl.backend: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER:krawl-gems}

# Storage Validation Configuration
storage:
  validation:
    max-file-size: ${STORAGE_MAX_FILE_SIZE:10485760} # 10MB in bytes
    allowed-content-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/webp
      - image/heic

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-min-256-bits}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30 days in milliseconds
  cookie-secure: ${JWT_COOKIE_SECURE:false} # Set to true in production (HTTPS)


# App configuration
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  password-reset:
    expiry-minutes: ${APP_PASSWORD_RESET_EXPIRY_MINUTES:30}
  registration:
    expiry-minutes: ${APP_REGISTRATION_EXPIRY_MINUTES:60}
  mail:
    # Email provider: 'smtp', 'sendgrid', 'resend', or 'mailjet'
    # Use 'mailjet', 'resend', or 'sendgrid' for Render deployments (SMTP ports are blocked)
    # Use 'smtp' for local development or platforms that support SMTP
    # Recommended: 'mailjet' (best free tier: 6,000/month, 200/day)
    provider: ${MAIL_PROVIDER:smtp}
    from: ${MAIL_FROM}
    fromName: ${MAIL_FROM_NAME:Krawl}
    # SendGrid API configuration (only needed if provider=sendgrid)
    sendgrid:
      api-key: ${SENDGRID_API_KEY:}
    # Resend API configuration (only needed if provider=resend)
    resend:
      api-key: ${RESEND_API_KEY:}
    # Mailjet API configuration (only needed if provider=mailjet)
    mailjet:
      api-key-public: ${MAILJET_API_KEY_PUBLIC:}
      api-key-private: ${MAILJET_API_KEY_PRIVATE:}

# CAPTCHA Configuration
captcha:
  provider: ${CAPTCHA_PROVIDER:hcaptcha} # hcaptcha | recaptcha
  secret: ${CAPTCHA_SECRET:}

# Actuator Configuration
# Health endpoints are used by Render for health checks and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      # Enable health probes for better container orchestration
      probes:
        enabled: true
        liveness-state:
          enabled: true
        readiness-state:
          enabled: true
  metrics:
    export:
      prometheus:
        enabled: false # Enable if using Prometheus